import {
  img_testimoni_1,
  img_testimoni_2,
  img_testimoni_3,
  img_testimoni_4,
  img_testimoni_5,
  img_testimoni_6,
  img_testimoni_7,
  img_testimoni_8,
  img_testimoni_9,
  img_testimoni_atika,
  img_testimoni_awdella,
  img_testimoni_beazakia,
  img_testimoni_chef,
  img_testimoni_dea_putri,
  img_testimoni_eca,
  img_testimoni_gigi,
  img_testimoni_gomez,
  img_testimoni_hadid,
  img_testimoni_juli,
  img_testimoni_meggie,
  img_testimoni_raditya_dika,
  img_testimoni_rieke,
  img_testimoni_shalfa,
  img_testimoni_yuli,
  img_testomoni_aisyah,
  img_testomoni_chandra,
} from 'assets/images';
import {useTranslation} from 'react-i18next';

export const useTestimoniInfluencerMockData = () => {
  const {t} = useTranslation();

  return [
    {
      id: 22,
      image: img_testimoni_raditya_dika,
      name: 'Raditya Dika',
      aliasName: '@raditya_dika',
      review: t('Home.testimoni.comment_22'),
    },
    {
      id: 1,
      image: img_testimoni_shalfa,
      name: 'Shalfa',
      aliasName: '@shalfaptr',
      review: t('Home.testimoni.comment_18'),
    },
    {
      id: 2,
      image: img_testimoni_dea_putri,
      name: 'Dea Putri and Friends',
      aliasName: '@deaputriim @naufansaaf',
      review: t('Home.testimoni.comment_19'),
    },
    {
      id: 3,
      image: img_testimoni_beazakia,
      name: 'Bunga Zakia',
      aliasName: '@beazakia',
      review: t('Home.testimoni.comment_20'),
    },
    {
      id: 4,
      image: img_testomoni_aisyah,
      name: 'Aisyaf Putri & Juan Daly',
      aliasName: '@aisyafputri & juandadaly',
      review: t('Home.testimoni.comment_21'),
    },

    {
      id: 5,
      image: img_testimoni_hadid,
      name: 'Fachrul Hadid',
      aliasName: '@fachrulhadid',
      review: t('Home.testimoni.comment_15'),
    },
    {
      id: 6,
      image: img_testimoni_eca,
      name: 'Eca Aura',
      aliasName: '@elsaajapasal',
      review: t('Home.testimoni.comment_1'),
    },
    {
      id: 7,
      image: img_testimoni_gomez,
      name: 'Mumuk Gomez',
      aliasName: '@mumukgomez',
      review: t('Home.testimoni.comment_16'),
    },
    {
      id: 8,
      image: img_testimoni_rieke,
      name: 'Rieke Meilani',
      aliasName: '@riekemeilanis',
      review: t('Home.testimoni.comment_2'),
    },
    {
      id: 9,
      image: img_testimoni_yuli,
      name: 'Yulie Nasution',
      aliasName: '@yulienasution.official',
      review: t('Home.testimoni.comment_3'),
    },
    {
      id: 10,
      image: img_testimoni_chef,
      name: 'Chef Yongki Gunawan',
      aliasName: '@yongki_gunawan_kue',
      review: t('Home.testimoni.comment_4'),
    },
    {
      id: 11,
      image: img_testimoni_1,
      name: 'Guntur LDP',
      aliasName: '@Elziwai',
      review: t('Home.testimoni.comment_5'),
    },
    {
      id: 12,
      image: img_testimoni_6,
      name: 'Mamun',
      aliasName: '@andre_perwira',
      review: t('Home.testimoni.comment_6'),
    },
    {
      id: 13,
      image: img_testimoni_7,
      name: 'Chelsya Laurent',
      aliasName: '@ChelsyaLaurent',
      review: t('Home.testimoni.comment_7'),
    },
    {
      id: 14,
      image: img_testimoni_8,
      name: 'Jeri Taufik',
      aliasName: '@WhatsGoodTV09',
      review: t('Home.testimoni.comment_8'),
    },
    {
      id: 15,
      image: img_testimoni_9,
      name: 'Ken&Grat',
      aliasName: '@kenandgrat',
      review: t('Home.testimoni.comment_9'),
    },
    {
      id: 16,
      image: img_testimoni_juli,
      name: 'Julioes21',
      aliasName: '@Sini Gue Ceritain',
      review: t('Home.testimoni.comment_10'),
    },
    {
      id: 17,
      image: img_testimoni_meggie,
      name: 'Maggie Kholine',
      aliasName: '@maggiekholine',
      review: t('Home.testimoni.comment_11'),
    },
    {
      id: 18,
      image: img_testomoni_chandra,
      name: 'Chandra Putra Negara',
      aliasName: '@chandraputranegara',
      review: t('Home.testimoni.comment_17'),
    },
    {
      id: 19,
      image: img_testimoni_gigi,
      name: 'Gigi Geraldine',
      aliasName: '@gigigeraldinee',
      review: t('Home.testimoni.comment_12'),
    },
    {
      id: 20,
      image: img_testimoni_awdella,
      name: 'Awdella',
      aliasName: '@awdella_',
      review: t('Home.testimoni.comment_13'),
    },
    {
      id: 21,
      image: img_testimoni_atika,
      name: 'Atika',
      aliasName: '@atiikazzz',
      review: t('Home.testimoni.comment_14'),
    },
  ];
};

export const customerTestimoniMockData = [
  {
    id: 1,
    image: img_testimoni_2,
  },
  {
    id: 2,
    image: img_testimoni_3,
  },
  {
    id: 3,
    image: img_testimoni_4,
  },
  {
    id: 4,
    image: img_testimoni_5,
  },
];
