# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  lane :deploy_internal do
    upload_to_play_store(
      json_key_data: ENV["GOOGLE_PLAY_JSON_KEY"],
      package_name: "com.getrideapp",
      track: "internal",
      aab: File.absolute_path('../app/build/outputs/bundle/productionRelease/app-production-release.aab')
    )
  end

  desc "Distribute Staging Build to Firebase"
  lane :distribute_staging do
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      service_credentials_file: ENV["FIREBASE_CREDENTIALS"],
      groups: "TESTERS",
      release_notes: "Staging Build for Testing"
    )
  end
end
