name: Build and Deploy Android app

on:
  push:
    branches:
      - dev

jobs:
  build:
    environment: STAGING_ENV
    runs-on: ubuntu-latest  # Ganti dari macOS ke Ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Fastlane
        run: sudo gem install fastlane -NV

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin  # 'temurin' lebih cepat dibandingkan 'adopt'
          cache: gradle

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Clear Cache & Reinstall Dependencies
        run: |
          rm -rf node_modules package-lock.json yarn.lock
          yarn cache clean
          yarn install --frozen-lockfile

      - name: Remove Hermes tarball
        run: rm -rf node_modules/react-native/sdks/download/hermes.tar.gz

      - name: Create .env File
        run: |
          echo "ENV=${{ vars.ENV }}" > .env.staging
          echo "APP_URL=${{ vars.APP_URL }}" >> .env.staging
          echo "URL_API=${{ vars.URL_API }}" >> .env.staging
          echo "URL_IMAGE=${{ vars.URL_IMAGE }}" >> .env.staging
          echo "MIDTRANS_CLIENT_KEY=${{ vars.MIDTRANS_CLIENT_KEY }}" >> .env.staging
          echo "API_MIDTRANS=${{ vars.API_MIDTRANS }}" >> .env.staging
          echo "APP_ID=${{ vars.APP_ID }}" >> .env.staging
          echo "API_MESSENGER=${{ vars.API_MESSENGER }}" >> .env.staging

      - name: Apply Patch
        run: npx patch-package

      - name: Clean Gradle
        run: cd android && ./gradlew clean

      - name: Build APK application
        run: |
          cd android
          ./gradlew assembleStagingRelease --parallel --daemon

      - name: Setup Fastlane
        run: |
          sudo apt-get update -y
          sudo apt-get install ruby-full -y
          gem install fastlane -NV

      - name: Upload APK to Firebase App Distribution
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          cd android
          fastlane distribute_staging
