name: Build and Deploy Android app

on:
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
  build:
    if: github.event.pull_request.merged == true
    environment: STAGING_ENV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Get PR Description
        id: pr_desc
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_BODY=$(gh pr view "$PR_NUMBER" --json body -q '.body' | tr -d '\r')
          echo "PR_BODY<<EOF" >> $GITHUB_ENV
          echo "$PR_BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV


      - name: Check if Build & Tagging Required
        id: check_tag
        run: |
          if echo "$PR_BODY" | grep -q "is_create_tag=true"; then
            echo "BUILD_AND_TAG=true" >> $GITHUB_ENV
          else
            echo "BUILD_AND_TAG=false" >> $GITHUB_ENV
          fi

      - name: Install Java
        if: env.BUILD_AND_TAG == 'true'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Node.js
        if: env.BUILD_AND_TAG == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Cache node_modules
        if: env.BUILD_AND_TAG == 'true'
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install Dependencies
        if: env.BUILD_AND_TAG == 'true'
        run: yarn install --frozen-lockfile

      - name: Remove Hermes tarball
        if: env.BUILD_AND_TAG == 'true'
        run: rm -rf node_modules/react-native/sdks/download/hermes.tar.gz

      - name: Create .env File
        if: env.BUILD_AND_TAG == 'true'
        run: |
          echo "ENV=${{ vars.ENV }}" > .env.staging
          echo "APP_URL=${{ vars.APP_URL }}" >> .env.staging
          echo "URL_API=${{ vars.URL_API }}" >> .env.staging
          echo "URL_IMAGE=${{ vars.URL_IMAGE }}" >> .env.staging
          echo "MIDTRANS_CLIENT_KEY=${{ vars.MIDTRANS_CLIENT_KEY }}" >> .env.staging
          echo "API_MIDTRANS=${{ vars.API_MIDTRANS }}" >> .env.staging
          echo "APP_ID=${{ vars.APP_ID }}" >> .env.staging
          echo "API_MESSENGER=${{ vars.API_MESSENGER }}" >> .env.staging

      - name: Auto Increment Version
        if: env.BUILD_AND_TAG == 'true'
        run: |
          BUILD_FILE="android/app/build.gradle"

          VERSION_NAME=$(grep -oP 'versionName\s+"\K[^"]+' $BUILD_FILE)
          VERSION_CODE=$(grep -oP 'versionCode\s+\K\d+' $BUILD_FILE)

          IFS='.' read -r -a version_parts <<< "$VERSION_NAME"
          version_parts[2]=$((version_parts[2] + 1))
          NEW_VERSION_NAME="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
          NEW_VERSION_CODE=$((VERSION_CODE + 1))

          sed -i "s/versionName \".*\"/versionName \"$NEW_VERSION_NAME\"/" $BUILD_FILE
          sed -i "s/versionCode .*/versionCode $NEW_VERSION_CODE/" $BUILD_FILE

          echo "NEW_VERSION_NAME=$NEW_VERSION_NAME" >> $GITHUB_ENV

      - name: Build APK application
        if: env.BUILD_AND_TAG == 'true'
        run: |
          cd android
          ./gradlew assembleStagingRelease --max-workers=2 --parallel --no-daemon

      - name: Commit Updated Version
        if: env.BUILD_AND_TAG == 'true'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/suma1892/testing-rent-car-app.git

          LAST_TAG=$(git tag --sort=-creatordate | head -n 1)
          
          if [ -z "$LAST_TAG" ]; then
            COMMIT_MESSAGES=$(git log --pretty=format:"- %s" --no-merges)
          else
            COMMIT_MESSAGES=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s" --no-merges)
          fi
          SHORT_COMMIT_MSG=$(echo "$COMMIT_MESSAGES" | cut -c1-100)

          RELEASE_NOTES="chore(release): bump version to $NEW_VERSION_NAME\n\n$SHORT_COMMIT_MSG"

          git add android/version.properties
          git commit -m "$RELEASE_NOTES"
          git push origin dev

      - name: Create Git Tag
        if: env.BUILD_AND_TAG == 'true'
        run: |
          git tag v${NEW_VERSION_NAME}-staging
          git push origin v${NEW_VERSION_NAME}-staging

      - name: Upload artifact to Firebase App Distribution
        if: env.BUILD_AND_TAG == 'true'
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: TESTERS
          file: android/app/build/outputs/apk/staging/release/app-staging-release.apk
