name: Build and Deploy Android app

on:
  push:
    branches:
      - dev

jobs:
  build:
    environment: STAGING_ENV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Dependencies
        run: |
          rm -rf node_modules yarn.lock package-lock.json
          yarn cache clean
          yarn install --frozen-lockfile

      - name: Remove Hermes tarball
        run: rm -rf node_modules/react-native/sdks/download/hermes.tar.gz

      - name: Create .env File
        run: |
          echo "ENV=${{ vars.ENV }}" > .env.staging
          echo "APP_URL=${{ vars.APP_URL }}" >> .env.staging
          echo "URL_API=${{ vars.URL_API }}" >> .env.staging
          echo "URL_IMAGE=${{ vars.URL_IMAGE }}" >> .env.staging
          echo "MIDTRANS_CLIENT_KEY=${{ vars.MIDTRANS_CLIENT_KEY }}" >> .env.staging
          echo "API_MIDTRANS=${{ vars.API_MIDTRANS }}" >> .env.staging
          echo "APP_ID=${{ vars.APP_ID }}" >> .env.staging
          echo "API_MESSENGER=${{ vars.API_MESSENGER }}" >> .env.staging

      - name: Apply Patch
        run: npx patch-package

      - name: Clean Gradle
        run: cd android && ./gradlew clean

      - name: Build APK application
        run: |
          cd android
          ./gradlew assembleStagingRelease --parallel --daemon

      - name: Setup Ruby & Bundler
        run: |
          sudo apt-get update -y
          sudo apt-get install ruby-full -y
          gem install bundler --user-install
          export GEM_HOME="$HOME/.gem"
          export PATH="$GEM_HOME/bin:$PATH"

      - name: Setup Fastlane & Install Plugin
        run: |
          export GEM_HOME="$HOME/.gem"
          export PATH="$GEM_HOME/bin:$PATH"
          gem install fastlane -NV --user-install
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Prepare Firebase Credentials
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" > android/app/firebase-credentials.json

      - name: Upload APK to Firebase App Distribution
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: android/app/firebase-credentials.json
        run: |
          cd android
          bundle exec fastlane distribute_staging
